"""Add visible column to GalleryImage class.

Revision ID: 05f4c026e8d0
Revises: 8e725fa3b19e
Create Date: 2017-10-29 09:04:47.363900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f4c026e8d0'
down_revision = '8e725fa3b19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.drop_column('visible')

    # ### end Alembic commands ###
