"""Added receipt column to RequestBooking class.

Revision ID: 8e725fa3b19e
Revises: 1fc56efcc6bb
Create Date: 2017-10-22 21:37:14.006320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e725fa3b19e'
down_revision = '1fc56efcc6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('receipt')

    # ### end Alembic commands ###
