"""Added excerpt and thumbnail columns to Event model.

Revision ID: a2614ce7519a
Revises: d70b635828f2
Create Date: 2017-05-07 09:24:37.146985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2614ce7519a'
down_revision = 'd70b635828f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excerpt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('excerpt')

    # ### end Alembic commands ###
